# Generated by Django 6.0 on 2025-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание задачи"),
        ),
    ]
