# Generated by Django 6.0 on 2025-12-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_user_options_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Срок выполнения"
            ),
        ),
    ]
